version: 2

references:
  build_config: &build_config
      docker:
        - image: circleci/node:8.9.4
      working_directory: ~/repo

  restore_cache: &restore_cache
    restore_cache:
      keys:
      - v1-dependencies-{{ checksum "package.json" }}

  save_cache: &save_cache
    save_cache:
      paths:
        - node_modules
      key: v1-dependencies-{{ checksum "package.json" }}

jobs:
  test:
    <<: *build_config
    steps:
      - checkout
      - <<: *restore_cache
      - run: npm install
      - <<: *save_cache
      - run: npm test
      - run: npm pack && mkdir pkg && mv *.tgz pkg
      - store_artifacts:
          path: pkg
          destination: pkg

  deploy:
    <<: *build_config
    steps:
      - checkout
      - <<: *restore_cache
      - run: npm install
      - <<: *save_cache
      - run: npm run build:demo
      - run: .circleci/set-git-identity.sh
      - run: .circleci/deploy-demo.sh

  publish:
    <<: *build_config
    steps:
      - checkout
      - <<: *restore_cache
      - run: npm install
      - <<: *save_cache
      - run: npm run build
      - run: 'echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc'
      - run: npm publish

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test

      - deploy:
          filters:
            branches:
              only: master
          requires:
            - test

      - publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
